[package]
name = "taktiny"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
numpy = "0.28.0"
pyo3 = "0.28.2"
safetensors = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
stubgen = ["pyo3/experimental-inspect"]

[lib]
name = "taktinylib"
crate-type = ["cdylib"]
path = "src/taktinylib/lib.rs"
