[project]
name = "destiny"
version = "0.0.1"
description = "A JAX library for neural network model development and pretrained model workflows."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "taktiny",
]

[tool.uv.sources]
taktiny = { git = "https://github.com/solitariusai/taktiny.git", rev = "experiment" }
